module.exports = [
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg", 
    title:"VS Code"
  },
  { 
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    title:"Git"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
    title:"GitHub"
  },
  { url:"https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg",
    title:"HTML"
  },
    { url:"https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg",
    title:"CSS"
  },
  {
    url:"https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-plain.svg",
    title:"JavaScript"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg",
    title:"Jest"
  },
  {
    url:"https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original.svg",
    title:"React"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg",
    title:"Redux"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
    title:"Docker"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
    title:"MySQL"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    title:"Node.js"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/express/express-original.svg",
    title:"Express"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mocha/mocha-plain.svg",
    title:"Mocha"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sequelize/sequelize-original.svg",
    title:"Sequelize"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original.svg",
    title:"Heroku"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    title:"TypeScript"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/firebase/firebase-plain-wordmark.svg",
    title:"Firebase"
  },
  {
    url:"https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
    title:"Sass"
  },
]
